"""
worker/tracker.py

Redis-backed tracker for ingestion job and per-file status.

Key structure:
  job:{job_id}                →  JSON  — job-level record
  job:{job_id}:file:{fname}   →  JSON  — per-file record
  job:{job_id}:total          →  int   — total file count (set once by orchestrator)
  job:{job_id}:done_count     →  int   — atomically incremented by cleanup_task
  job:{job_id}:failed_count   →  int   — atomically incremented on any file failure

All keys share the same TTL (JOB_TRACKER_TTL_S, default 7 days).
TTL is refreshed on every write so active jobs never expire mid-run.

Design decisions:
  - All tracker calls are wrapped in try/except. A Redis failure must NEVER
    crash the pipeline. Data integrity (Azure Search) > status visibility.
  - Completion check uses atomic INCR counters to avoid race conditions when
    multiple cleanup_task workers finish simultaneously.
  - job_id is a UUID4 string generated by the API layer, not here.
"""

import json
from datetime import datetime, timezone
from typing import Literal
import shutil
import redis

from colep_ai.core.config import settings
from colep_ai.core.logger import get_logger

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

JobStatus = Literal["pending", "running", "completed", "partial", "failed"]
FileStatus = Literal[
    "pending",
    "ingesting",
    "ingesting_done",
    "indexing",
    "done",
    "failed",
]

# ---------------------------------------------------------------------------
# Redis client
# ---------------------------------------------------------------------------

# Lazy singleton — created on first use, not at import time.
# This avoids connection errors during testing or when Redis is not yet up.
_redis: redis.Redis | None = None


def _get_redis() -> redis.Redis:
    global _redis
    if _redis is None:
        _redis = redis.Redis.from_url(
            settings.REDIS_URL,
            decode_responses=True,
            socket_connect_timeout=5,
            socket_timeout=5,
        )
    return _redis


# ---------------------------------------------------------------------------
# Key helpers
# ---------------------------------------------------------------------------

def _job_key(job_id: str) -> str:
    return f"job:{job_id}"

def _file_key(job_id: str, filename: str) -> str:
    return f"job:{job_id}:file:{filename}"

def _total_key(job_id: str) -> str:
    return f"job:{job_id}:total"

def _done_key(job_id: str) -> str:
    return f"job:{job_id}:done_count"

def _failed_key(job_id: str) -> str:
    return f"job:{job_id}:failed_count"

def _now() -> str:
    return datetime.now(timezone.utc).isoformat()

TTL = settings.JOB_TRACKER_TTL_S

# ---------------------------------------------------------------------------
# Job-level operations
# ---------------------------------------------------------------------------

def create_job(job_id: str, sharepoint_folder_path: str) -> None:
    """Called by API layer immediately after job_id is generated."""
    try:
        r = _get_redis()
        payload = json.dumps({
            "job_id": job_id,
            "sharepoint_folder_path": sharepoint_folder_path,
            "status": "pending",
            "total_files": 0,
            "completed_files": 0,
            "failed_files": 0,
            "started_at": _now(),
            "completed_at": None,
        })
        r.set(_job_key(job_id), payload, ex=TTL)
    except Exception:
        logger.exception(f"[tracker] create_job failed for {job_id}")


def update_job_status(job_id: str, status: JobStatus, total_files: int | None = None) -> None:
    """Update job status and optionally set total_files (called by orchestrator)."""
    try:
        r = _get_redis()
        raw = r.get(_job_key(job_id))
        if raw is None:
            logger.warning(f"[tracker] update_job_status: job {job_id} not found in Redis")
            return
        record = json.loads(raw)
        record["status"] = status
        if total_files is not None:
            record["total_files"] = total_files
            r.set(_total_key(job_id), total_files, ex=TTL)
        if status in ("completed", "partial", "failed"):
            record["completed_at"] = _now()
        r.set(_job_key(job_id), json.dumps(record), ex=TTL)
    except Exception:
        logger.exception(f"[tracker] update_job_status failed for {job_id}")


def get_job(job_id: str) -> dict | None:
    """Returns the job record with live counter values merged in."""
    try:
        r = _get_redis()
        raw = r.get(_job_key(job_id))
        if raw is None:
            return None
        record = json.loads(raw)
        # Merge live atomic counters into record for accurate status response
        done = r.get(_done_key(job_id))
        failed = r.get(_failed_key(job_id))
        record["completed_files"] = int(done) if done else 0
        record["failed_files"] = int(failed) if failed else 0
        return record
    except Exception:
        logger.exception(f"[tracker] get_job failed for {job_id}")
        return None


def find_active_job_by_path(sharepoint_folder_path: str) -> str | None:
    """
    Returns job_id if an active (pending/running) job exists for the same
    SharePoint folder path. Used to prevent duplicate ingestion runs.
    Scans Redis keys — acceptable at low job volume (max ~50 concurrent jobs).
    """
    try:
        r = _get_redis()
        for key in r.scan_iter("job:*"):
            # Skip counter and file keys — only check top-level job keys
            if ":file:" in key or key.endswith((":total", ":done_count", ":failed_count")):
                continue
            raw = r.get(key)
            if raw is None:
                continue
            record = json.loads(raw)
            if (
                record.get("sharepoint_folder_path") == sharepoint_folder_path
                and record.get("status") in ("pending", "running")
            ):
                return record["job_id"]
    except Exception:
        logger.exception("[tracker] find_active_job_by_path failed")
    return None

# ---------------------------------------------------------------------------
# File-level operations
# ---------------------------------------------------------------------------

def create_file_record(job_id: str, filename: str, folder_name: str = "") -> None:
    """Called by orchestrator for each discovered .xlsx file."""
    try:
        r = _get_redis()
        payload = json.dumps({
            "job_id": job_id,
            "filename": filename,
            "folder_name": folder_name,  
            "status": "pending",
            "error": None,
            "started_at": None,
            "completed_at": None,
        })
        r.set(_file_key(job_id, filename), payload, ex=TTL)
    except Exception:
        logger.exception(f"[tracker] create_file_record failed for {job_id}/{filename}")


def update_file_status(
    job_id: str,
    filename: str,
    status: FileStatus,
    error: str | None = None,
) -> None:
    try:
        r = _get_redis()
        key = _file_key(job_id, filename)
        raw = r.get(key)
        if raw is None:
            logger.warning(f"[tracker] update_file_status: file record not found {job_id}/{filename}")
            return
        record = json.loads(raw)
        record["status"] = status
        if error is not None:
            record["error"] = error
        if status == "ingesting" and record.get("started_at") is None:
            record["started_at"] = _now()
        if status in ("done", "failed"):
            record["completed_at"] = _now()
        r.set(key, json.dumps(record), ex=TTL)
    except Exception:
        logger.exception(f"[tracker] update_file_status failed for {job_id}/{filename}")


def get_all_file_records(job_id: str) -> list[dict]:
    """Returns all per-file records for a job. Used by status endpoint."""
    try:
        r = _get_redis()
        pattern = f"job:{job_id}:file:*"
        records = []
        for key in r.scan_iter(pattern):
            raw = r.get(key)
            if raw:
                records.append(json.loads(raw))
        return records
    except Exception:
        logger.exception(f"[tracker] get_all_file_records failed for {job_id}")
        return []

# ---------------------------------------------------------------------------
# Completion check — called by cleanup_task after every file finishes
# ---------------------------------------------------------------------------

def record_file_done(job_id: str) -> None:
    """
    Atomically increment done counter.
    Check if all files are accounted for and finalize job status if so.
    """
    _increment_and_check(job_id, done=True)


def record_file_failed(job_id: str) -> None:
    """
    Atomically increment failed counter.
    Check if all files are accounted for and finalize job status if so.
    """
    _increment_and_check(job_id, done=False)


def _increment_and_check(job_id: str, done: bool) -> None:
    """
    Increment the appropriate counter then check if job is complete.

    Completion rule:
      done_count + failed_count == total_files → job is finished
      all done    → "completed"
      mix         → "partial"
      all failed  → "failed"
    """
    try:
        r = _get_redis()

        if done:
            current_done = r.incr(_done_key(job_id))
            r.expire(_done_key(job_id), TTL)
            current_failed = int(r.get(_failed_key(job_id)) or 0)
        else:
            current_done = int(r.get(_done_key(job_id)) or 0)
            current_failed = r.incr(_failed_key(job_id))
            r.expire(_failed_key(job_id), TTL)

        total_raw = r.get(_total_key(job_id))
        if total_raw is None:
            logger.warning(f"[tracker] total key missing for job {job_id}")
            return

        total = int(total_raw)
        accounted = current_done + current_failed

        if accounted < total:
            # Not all files finished yet
            return

        # All files accounted for — finalize job
        if current_failed == 0:
            final_status: JobStatus = "completed"
        elif current_done == 0:
            final_status = "failed"
        else:
            final_status = "partial"

        update_job_status(job_id, final_status)
        logger.info(
            f"[tracker] job {job_id} finalized → {final_status} "
            f"(done={current_done} failed={current_failed} total={total})"
        )
        # Delete UUID downloads folder after all files are processed
        try:
            local_dir = settings.downloads_dir(job_id)
            if local_dir.exists():
                shutil.rmtree(local_dir, ignore_errors=True)
                logger.info(f"[tracker] job={job_id} deleted downloads folder: {local_dir}")
            else:
                logger.info(f"[tracker] job={job_id} downloads folder already gone: {local_dir}")
        except Exception:
            logger.exception(f"[tracker] job={job_id} failed to delete downloads folder")
            
    except Exception:
        logger.exception(f"[tracker] _increment_and_check failed for {job_id}")